name: Test API Key

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Save secret to file
        run: echo "${{ secrets.REACT_APP_FIREBASE_API_KEY }}" > api_key.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api_key
          path: api_key.txt
