name: Test API Key

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Print masked API key (sanity check)
        run: echo "Using API Key:${{ secrets.REACT_APP_FIREBASE_API_KEY }}"  # this will be masked in logs
        
      - name: Test API call
        run: |
          curl -i -H "Authorization: Bearer ${{ secrets.REACT_APP_FIREBASE_API_KEY }}" https://your-api.com/test
